### ISSUE TITLE
Threads not being saved

### ISSUE THREAD

**Issue by voshond** [kbravh/obsidian-tweet-to-markdown#40]
Hey,

Been trying to save threads with no avail. Using the twitter token for the auth, if that matters.

Here is an example: https://twitter.com/HurynPawel/status/1583117035336499202

I go to the twitter button, add the URL, make sure the save thread is enabled and all it does it's saving only the tweet provided, all the others aren't being saved.

Am i doing something wrong?

**Comment by kbravh** [comment]
Hi @voshond, due to a limitation of the Twitter API, you have to use the url of the last tweet in the thread, and the plugin works its way back up. 

So for the thread you provided, try using this link: https://twitter.com/HurynPawel/status/1583117068630560768

Let me know if you have any other issues and I'll be happy to help out!

**Comment by voshond** [comment]
Hey @kbravh!

That worked, thanks for pointing this out. I would suggest maybe adding a description on how this behaviour works in the modal, so it's a bit more intuitive (:

Cheers
-Martin

**Comment by kbravh** [comment]
@voshond Great suggestion! I've added an issue to track that here: https://github.com/kbravh/obsidian-tweet-to-markdown/issues/41
