### ISSUE TITLE
Request failed status 403

### ISSUE THREAD

**Issue by mturilin** [kbravh/obsidian-tweet-to-markdown#45]
I set up the plugin as described, and generated API bearer token with Twitter. However, when I try downloading a tweet I see "Request failed status 403" message.

How can I troubleshoot?

**Comment by anuan1** [comment]
I encounter the same issue after allocating a newly created bearer token.

Any information on how to solve this?

**Comment by kbravh** [comment]
Unfortunately, Twitter has shut down access to their API, and there is no way for me to reactivate it currently. You will have to apply for your own bearer token in order to use this tool.

Please follow the instructions in the [Bearer token guide](https://github.com/kbravh/obsidian-tweet-to-markdown/blob/main/BearerTokenGuide.md).
